// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrmfihasicpqskkeuqik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybWZpaGFzaWNwcXNra2V1cWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTM0NTQsImV4cCI6MjA3NjA4OTQ1NH0.60zpR3KBv6gssRfaAZhav5Dkgw-aN_234JjaULazUGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});